using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Jvm.NET.SourceGenerator;

/// <summary>
/// Jvm.NET 的 Source Generator：扫描 [JavaClass] 特性和 .jn.json 文件，
/// 生成 Java 类的强类型 C# 封装。
/// </summary>
[Generator]
public sealed class JavaClassGenerator : IIncrementalGenerator
{
    private const string JavaClassAttributeFullName = "Jvm.NET.Abstractions.JavaClassAttribute";
    private const string JavaMethodAttributeFullName = "Jvm.NET.Abstractions.JavaMethodAttribute";
    private const string JavaFieldAttributeFullName = "Jvm.NET.Abstractions.JavaFieldAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 特性模式：扫描 [JavaClass] 标记的分部类
        var classDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                JavaClassAttributeFullName,
                predicate: IsPartialClassDeclaration,
                transform: TransformClassDeclaration)
            .Where(c => c is not null)
            .Select((c, _) => c!);

        context.RegisterSourceOutput(classDeclarations, EmitClassFromAttribute);

        // JSON 模式：扫描 .jn.json 文件
        var jsonFiles = context.AdditionalTextsProvider
            .Where(f => f.Path.EndsWith(".jn.json", System.StringComparison.OrdinalIgnoreCase))
            .Select((file, _) => (file.Path, Content: file.GetText()?.ToString() ?? string.Empty))
            .Where(f => !string.IsNullOrEmpty(f.Content));

        context.RegisterSourceOutput(jsonFiles, EmitClassFromJson);
    }

    private static bool IsPartialClassDeclaration(SyntaxNode node, CancellationToken _)
        => node is ClassDeclarationSyntax c && c.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword));

    private static ClassSpec? TransformClassDeclaration(GeneratorAttributeSyntaxContext ctx, CancellationToken _)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.TargetNode;
        var classSymbol = ctx.TargetSymbol as INamedTypeSymbol;
        if (classSymbol is null) return null;

        var attr = ctx.Attributes.FirstOrDefault();
        if (attr is null || attr.ConstructorArguments.Length == 0) return null;

        var javaClassName = attr.ConstructorArguments[0].Value as string;
        if (string.IsNullOrEmpty(javaClassName)) return null;

        var spec = new ClassSpec
        {
            Namespace = classSymbol.ContainingNamespace.IsGlobalNamespace ? null : classSymbol.ContainingNamespace.ToDisplayString(),
            ClassName = classSymbol.Name,
            JavaClassName = javaClassName!,
            Methods = new List<MethodSpec>(),
        };

        // 扫描标记了 [JavaMethod] 的 partial 方法定义部分
        foreach (var member in classSymbol.GetMembers())
        {
            if (member is not IMethodSymbol method) continue;
            if (!method.IsPartialDefinition) continue; // 只处理 partial 定义部分，跳过实现部分

            var methodAttr = member.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == JavaMethodAttributeFullName);
            if (methodAttr is null) continue;

            var javaMethodName = methodAttr.ConstructorArguments[0].Value as string ?? method.Name;
            var javaSignature = methodAttr.ConstructorArguments[1].Value as string ?? "";
            var isStatic = false;
            foreach (var named in methodAttr.NamedArguments)
            {
                if (named.Key == "IsStatic" && named.Value.Value is bool b)
                    isStatic = b;
            }

            spec.Methods.Add(new MethodSpec
            {
                MethodName = method.Name,
                JavaMethodName = javaMethodName,
                JavaSignature = javaSignature,
                IsStatic = isStatic,
                ReturnType = method.ReturnType.ToDisplayString(),
                Parameters = method.Parameters.Select(p => new ParamSpec
                {
                    Name = p.Name,
                    Type = p.Type.ToDisplayString(),
                }).ToList(),
            });
        }

        return spec.Methods.Count > 0 ? spec : null;
    }

    private static void EmitClassFromAttribute(SourceProductionContext ctx, ClassSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>由 Jvm.NET Source Generator 生成。请勿手动修改。</auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (spec.Namespace is not null)
        {
            sb.AppendLine($"namespace {spec.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"public partial class {spec.ClassName}");
        sb.AppendLine("{");

        foreach (var method in spec.Methods)
        {
            var returnType = method.ReturnType == "void" ? "void" : method.ReturnType;
            var paramList = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
            sb.AppendLine($"    public partial {returnType} {method.MethodName}({paramList})");
            sb.AppendLine("    {");

            // 构建参数转换
            var argList = string.Join(", ", method.Parameters.Select(p => ConvertParamToJvmValue(p)));
            var invokeCall = method.IsStatic
                ? $"InvokeStatic(\"{method.JavaMethodName}\", \"{method.JavaSignature}\"{(string.IsNullOrEmpty(argList) ? "" : ", " + argList)})"
                : $"Invoke(\"{method.JavaMethodName}\", \"{method.JavaSignature}\"{(string.IsNullOrEmpty(argList) ? "" : ", " + argList)})";

            if (method.ReturnType == "void")
            {
                sb.AppendLine($"        {invokeCall};");
            }
            else
            {
                var returnExpr = ConvertJvmValueToReturn(method.ReturnType, invokeCall);
                sb.AppendLine($"        return {returnExpr};");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        if (spec.Namespace is not null)
            sb.AppendLine("}");

        var hintName = (spec.Namespace is null ? "" : spec.Namespace.Replace('.', '_') + "_") + spec.ClassName;
        ctx.AddSource($"{hintName}.g.cs", sb.ToString());
    }

    private static void EmitClassFromJson(SourceProductionContext ctx, (string Path, string Content) jsonFile)
    {
        JsonClassModel? model;
        try
        {
            model = JsonSerializer.Deserialize<JsonClassModel>(jsonFile.Content);
        }
        catch
        {
            return;
        }

        if (model?.Classes is null || model.Classes.Count == 0) return;

        foreach (var cls in model.Classes)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>由 Jvm.NET Source Generator (JSON 模式) 生成。请勿手动修改。</auto-generated>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Jvm.NET.Abstractions;");
            sb.AppendLine();

            var ns = string.IsNullOrEmpty(cls.Namespace) ? "Generated" : cls.Namespace!;
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            sb.AppendLine($"public sealed class {cls.CsName} : JavaObject, IDisposable");
            sb.AppendLine("{");

            // 默认构造函数
            var ctorSig = string.IsNullOrEmpty(cls.ConstructorSignature) ? "()V" : cls.ConstructorSignature!;
            sb.AppendLine($"    public {cls.CsName}(IJvmInvoker invoker)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var obj = invoker.NewObject(invoker.LoadClass(\"{cls.Name}\"), \"{ctorSig}\");");
            sb.AppendLine("        Attach(obj, invoker);");
            sb.AppendLine("    }");
            sb.AppendLine();

            // 包装构造函数
            sb.AppendLine($"    public {cls.CsName}(IJvmInvoker invoker, JvmObject existing)");
            sb.AppendLine("    {");
            sb.AppendLine("        Attach(existing, invoker);");
            sb.AppendLine("    }");
            sb.AppendLine();

            // 方法
            if (cls.Methods is not null)
            {
                foreach (var method in cls.Methods)
                {
                    var csReturnType = string.IsNullOrEmpty(method.ReturnType) ? "void" : method.ReturnType!;
                    var paramList = string.IsNullOrEmpty(method.Parameters) ? "" : method.Parameters!;
                    sb.AppendLine($"    public {csReturnType} {method.CsName}({paramList})");
                    sb.AppendLine("    {");

                    // 解析参数名（简化处理：假设参数格式为 "Type name, Type2 name2"）
                    var args = string.IsNullOrEmpty(paramList) ? "" : ", " + string.Join(", ",
                        paramList.Split(',').Select(p => p.Trim().Split(' ').Last().Trim()));

                    var invokeCall = method.IsStatic
                        ? $"InvokeStatic(\"{method.Name}\", \"{method.Signature}\"{args})"
                        : $"Invoke(\"{method.Name}\", \"{method.Signature}\"{args})";

                    if (csReturnType == "void")
                    {
                        sb.AppendLine($"        {invokeCall};");
                    }
                    else
                    {
                        var returnExpr = ConvertJvmValueToReturn(csReturnType, invokeCall);
                        sb.AppendLine($"        return {returnExpr};");
                    }

                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("}");
            sb.AppendLine("}");

            var fileName = ns.Replace('.', '_') + "_" + cls.CsName;
            ctx.AddSource($"{fileName}.g.cs", sb.ToString());
        }
    }

    // ---- 参数/返回值转换辅助 ----

    private static string ConvertParamToJvmValue(ParamSpec p)
    {
        return p.Type switch
        {
            "Jvm.NET.Abstractions.JvmValue" or "JvmValue" => p.Name,
            "string" or "string?" => $"TypeMapper.FromClr({p.Name}, Invoker)",
            "int" => $"JvmValue.FromInt({p.Name})",
            "long" => $"JvmValue.FromLong({p.Name})",
            "double" => $"JvmValue.FromDouble({p.Name})",
            "float" => $"JvmValue.FromFloat({p.Name})",
            "bool" => $"JvmValue.FromBoolean({p.Name})",
            "byte" => $"JvmValue.FromByte({p.Name})",
            "char" => $"JvmValue.FromChar({p.Name})",
            "short" => $"JvmValue.FromShort({p.Name})",
            "Jvm.NET.Abstractions.JvmObject" or "JvmObject" => $"JvmValue.FromObject({p.Name}.Handle)",
            _ => $"TypeMapper.FromClr({p.Name}, Invoker)",
        };
    }

    private static string ConvertJvmValueToReturn(string returnType, string invokeCall)
    {
        return returnType switch
        {
            "Jvm.NET.Abstractions.JvmValue" or "JvmValue" => invokeCall,
            "int" => $"{invokeCall}.AsInt()",
            "long" => $"{invokeCall}.AsLong()",
            "double" => $"{invokeCall}.AsDouble()",
            "float" => $"{invokeCall}.AsFloat()",
            "bool" => $"{invokeCall}.AsBoolean()",
            "byte" => $"{invokeCall}.AsByte()",
            "char" => $"{invokeCall}.AsChar()",
            "short" => $"{invokeCall}.AsShort()",
            "string" or "string?" => $"TypeMapper.ToString({invokeCall}, Invoker)",
            "void" => invokeCall,
            _ => $"TypeMapper.ToClr<{returnType}>({invokeCall}, Invoker)",
        };
    }

    // ---- 模型类 ----

    private sealed class ClassSpec
    {
        public string? Namespace { get; set; }
        public string ClassName { get; set; } = "";
        public string JavaClassName { get; set; } = "";
        public List<MethodSpec> Methods { get; set; } = new();
    }

    private sealed class MethodSpec
    {
        public string MethodName { get; set; } = "";
        public string JavaMethodName { get; set; } = "";
        public string JavaSignature { get; set; } = "";
        public bool IsStatic { get; set; }
        public string ReturnType { get; set; } = "";
        public List<ParamSpec> Parameters { get; set; } = new();
    }

    private sealed class ParamSpec
    {
        public string Name { get; set; } = "";
        public string Type { get; set; } = "";
    }

    // JSON 模型
    private sealed class JsonClassModel
    {
        public List<JsonClassDef>? Classes { get; set; }
    }

    private sealed class JsonClassDef
    {
        public string Name { get; set; } = "";
        public string CsName { get; set; } = "";
        public string? Namespace { get; set; }
        public string? ConstructorSignature { get; set; }
        public List<JsonMethodDef>? Methods { get; set; }
    }

    private sealed class JsonMethodDef
    {
        public string Name { get; set; } = "";
        public string Signature { get; set; } = "";
        public string CsName { get; set; } = "";
        public string? ReturnType { get; set; }
        public string? Parameters { get; set; }
        public bool IsStatic { get; set; }
    }
}
